---
- name: Install memcached
  apt: name={{ item }} state=present
  with_items:
    - memcached
    - libmemcached-tools
  notify: Restart php

- name: Create /etc/memcached.conf
  template: src=memcached.conf.j2 dest=/etc/memcached.conf owner=root group=root mode=0644
  notify: Restart memcached
