#!/bin/bash

export AWS_DEFAULT_PROFILE=default
export AWS_DEFAULT_REGION=us-east-1

export AWS_PROFILE=${AWS_DEFAULT_PROFILE}

EC2_INSTANCE_TYPE_DEFAULT="t2.micro"
EC2_INSTANCE_TYPE_NAT="t2.micro"
#EC2_INSTANCE_TYPE_LAMP="t2.medium"
EC2_INSTANCE_TYPE_LAMP="t2.small"

EC2_AMI_DEFAULT="ami-432eb53c"
EC2_AMI_NAT="ami-54ca472b"
EC2_AMI_LAMP="ami-432eb53c"

EC2_CREATE_RESOURCE_SLEEP_DEFAULT=2

DEFAULTS_LOADED=true
