#!/bin/bash

export AWS_DEFAULT_PROFILE=samtny
export AWS_DEFAULT_REGION=us-east-1

EC2_INSTANCE_TYPE_DEFAULT="t2.micro"
EC2_AMI_DEFAULT="ami-432eb53c"
EC2_AMI_NAT_DEFAULT="ami-54ca472b"
EC2_CREATE_RESOURCE_SLEEP_DEFAULT=2

DEFAULTS_LOADED=true
