---
- name: Add ubuntu user to www-data group
  user:
    name: ubuntu
    groups: www-data
    append: yes

- name: Create pf3 docroot
  file: path={{ pf3server_docroot }} state=directory owner=ubuntu group=ubuntu mode=0775

- name: Create pf3 ssl
  file: path={{ pf3server_ssl }} state=directory owner=ubuntu group=www-data mode=0740

- name: Create pf3 database
  mysql_db: name={{ pf3server_db_name }} state=present collation="utf8mb4_general_ci" encoding="utf8mb4"

- name: Create pf3 database user
  mysql_user: name={{ pf3server_db_user }} password={{ pf3server_db_password }} priv="{{ pf3server_db_name }}.*:ALL" state=present

- name: Create pf3 cache folder
  file: path={{ pf3server_docroot }}/cache state=directory owner=ubuntu group=www-data mode=0775

- name: Create /home/ubuntu/.pf3.my.cnf
  template: src=.pf3.my.cnf.j2 dest=/home/ubuntu/.pf3.my.cnf owner=ubuntu group=ubuntu mode=0644

- name: Create /home/ubuntu/pf3_scrape.sh
  template: src=scrape.sh.j2 dest=/home/ubuntu/pf3_scrape.sh owner=ubuntu group=ubuntu mode=0755

- name: Create /home/ubuntu/pf3_logrotate.sh
  template: src=logrotate.sh.j2 dest=/home/ubuntu/pf3_logrotate.sh owner=ubuntu group=ubuntu mode=0755

- name: Create /home/ubuntu/pf3_backup.sh
  template: src=backup.sh.j2 dest=/home/ubuntu/pf3_backup.sh owner=ubuntu group=ubuntu mode=0755

- name: Create pf3 scrape cron job
  cron: user="ubuntu" name="pf3 scrape cron" hour="19" minute="2" job="/home/ubuntu/pf3_scrape.sh >> /home/ubuntu/logs/pf3_scrape.log 2>&1"

- name: Create pf3 logrotate cron job
  cron: user="ubuntu" name="pf3 logrotate cron" hour="19" minute="3" job="/home/ubuntu/pf3_logrotate.sh"

- name: Create pf3 backup cron job
  cron: user="ubuntu" name="pf3 backup cron" hour="19" minute="12" job="/home/ubuntu/pf3_backup.sh >> /home/ubuntu/logs/pf3_backup.sh.log 2>&1"
