---
- name: Install apache
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - apache2-utils
    - apache2-doc

- name: Create /etc/apache2/apache2.conf
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/mods-enabled/headers.load
  file: src=../mods-available/headers.load dest=/etc/apache2/mods-enabled/headers.load state=link owner=root group=root mode=0644
  notify: Restart apache

#- name: Create /etc/apache2/conf-available/mpm-worker.conf
#  template: src=mpm-worker.conf.j2 dest=/etc/apache2/conf-available/mpm-worker.conf owner=root group=root mode=0644
#  notify: Restart apache

#- name: Create /etc/apache2/conf-enabled/mpm-worker.conf
#  file: src=../conf-available/mpm-worker.conf dest=/etc/apache2/conf-enabled/mpm-worker.conf state=link owner=root group=root mode=0644
#  notify: Restart apache

- name: Create /etc/apache2/conf-available/fqdn.conf
  template: src=fqdn.conf.j2 dest=/etc/apache2/conf-available/fqdn.conf owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-enabled/fqdn.conf
  file: src=../conf-available/fqdn.conf dest=/etc/apache2/conf-enabled/fqdn.conf state=link owner=root group=root mode=0644
  notify: Restart apache

#- name: Remove /etc/apache2/sites-enabled/000-default.conf
#  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Create /etc/apache2/conf-available/security.conf
  template: src=security.conf.j2 dest=/etc/apache2/conf-available/security.conf owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-enabled/security.conf
  file: src=../conf-available/security.conf dest=/etc/apache2/conf-enabled/security.conf state=link owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-available/pci.conf
  template: src=pci.conf.j2 dest=/etc/apache2/conf-available/pci.conf owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-enabled/pci.conf
  file: src=../conf-available/pci.conf dest=/etc/apache2/conf-enabled/pci.conf state=link owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-available/ec2.conf
  template: src=ec2.conf.j2 dest=/etc/apache2/conf-available/ec2.conf owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-enabled/ec2.conf
  file: src=../conf-available/ec2.conf dest=/etc/apache2/conf-enabled/ec2.conf state=link owner=root group=root mode=0644
  notify: Restart apache

- name: Enable apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - proxy
    - proxy_fcgi
    - actions
    - deflate
    - expires
    - headers
    - setenvif

  notify: Restart apache

#- name: Set apache mime.types
#  template: src=mime.types dest=/etc/apache/mime.types
#  notify: Restart apache

- name: Ensure apache service state
  service: name=apache2 state=started
