---
- name: Install apache
  apt: name={{ item }} state=present
  with_items:
    - apache2-mpm-worker
    - apache2-threaded-dev
    - apache2-utils
    - libapache2-mod-fastcgi

- name: Create /etc/apache2/conf-available/mpm-worker.conf
  template: src=mpm-worker.conf.j2 dest=/etc/apache2/conf-available/mpm-worker.conf owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-enabled/mpm-worker.conf
  file: src=../conf-available/mpm-worker.conf dest=/etc/apache2/conf-enabled/mpm-worker.conf state=link owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-available/php-fpm.conf
  template: src=php-fpm.conf.j2 dest=/etc/apache2/conf-available/php-fpm.conf owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-enabled/php-fpm.conf
  file: src=../conf-available/php-fpm.conf dest=/etc/apache2/conf-enabled/php-fpm.conf state=link owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-available/fqdn.conf
  template: src=fqdn.conf.j2 dest=/etc/apache2/conf-available/fqdn.conf owner=root group=root mode=0644
  notify: Restart apache

- name: Create /etc/apache2/conf-enabled/fqdn.conf
  file: src=../conf-available/fqdn.conf dest=/etc/apache2/conf-enabled/fqdn.conf state=link owner=root group=root mode=0644
  notify: Restart apache

- name: Remove /etc/apache2/sites-enabled/000-default.conf
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Enable apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - fastcgi
    - actions
    - deflate
    - expires
  notify: Restart apache

#- name: Set apache mime.types
#  template: src=mime.types dest=/etc/apache/mime.types
#  notify: Restart apache

- name: Ensure apache service state
  service: name=apache2 state=started
