---
- name: Create /home/ubuntu/backup.sh
  template: src=backup.sh.j2 dest=/home/ubuntu/backup.sh owner=ubuntu group=ubuntu mode=0755

- name: Create /home/ubuntu/restore.sh
  template: src=restore.sh.j2 dest=/home/ubuntu/restore.sh owner=ubuntu group=ubuntu mode=0755

- name: Create /home/ubuntu/logs
  file: path=/home/ubuntu/logs state=directory owner=ubuntu group=ubuntu mode=0755

- name: Create pf3 backup cron job
  cron: name="pf3 backup cron" hour="12" minute="19" job="/home/ubuntu/backup.sh >> /home/ubuntu/logs/backup.sh.log 2>&1"

- name: Create pf3 backup log rotation cron job
  cron: name="pf3 backup log rotation cron" hour="13" minute="19" job="/usr/bin/savelog -n -c 30 /home/ubuntu/logs/backup.sh.log > /dev/null 2>&1"
