---
- name: Install php
  apt: name={{ item }} state=present
  notify:
    - Restart php
    - Restart apache
  with_items:
    - php7.2-fpm
    - libapache2-mod-php7.2
    - php7.2-fpm
    - php7.2-cli
    - php7.2-curl
    - php7.2-mysql
    - php7.2-sqlite3
    - php7.2-gd
    - php-pear
    - php7.2-dev
    - build-essential
    - checkinstall
    - php7.2-mbstring
    - php7.2-dom
    - php7.2-memcached
    - php7.2-igbinary

- name: Ensure php.ini
  template: src=php.ini.j2 dest=/etc/php/7.2/fpm/php.ini owner=root group=root mode=0644
  notify: Restart php

- name: Ensure www.conf
  template: src=www.conf.j2 dest=/etc/php/7.2/fpm/pool.d/www.conf owner=root group=root mode=0644
  notify: Restart php

- name: Create /etc/php/7.2/mods-available/memcached.ini
  template: src=memcached.ini.j2 dest=/etc/php/7.2/mods-available/memcached.ini owner=root group=root mode=0644
  notify: Restart php

- name: Create /etc/php/7.2/fpm/conf.d/25-memcached.ini
  file: src=/etc/php/7.2/mods-available/memcached.ini dest=/etc/php/7.2/fpm/conf.d/25-memcached.ini state=link owner=root group=root mode=0644
  notify: Restart php

- name: Ensure php7.2-fpm state
  service: name=php7.2-fpm state=started
