- name: apply common configuration to all nodes
  hosts: all
  become: true
  pre_tasks:
    - apt: update_cache=yes
  roles:
    - common

- name: configure and deploy lamp
  hosts: tag_Service_lamp
  become: true
  roles:
    - common
    - pf3
  vars_files:
    - ../config/config.ec2.yml
    - ../credentials.yml
  tags:
    - lamp
