- name: apply common configuration to all nodes
  hosts: all
  become: true
  pre_tasks:
    - apt: update_cache=yes
  roles:
    - common

- name: configure and deploy lamp
  hosts: tag_Service_lamp
  become: true
  roles:
    - common
    - php74
    - pf3
    - pf3admin
    - samology
    - hardpuzzle
  vars_files:
    - ../config.yml
    - ../credentials.yml
  tags:
    - lamp
