---
- name: Create composer installer script
  template: src=install_composer.sh dest=/home/ubuntu/install_composer.sh owner=ubuntu group=ubuntu mode=0755

- name: Execute composer install script
  shell: /home/ubuntu/install_composer.sh creates=/usr/local/bin/composer
