---
- name: Install xdebug
  apt: name={{ item }} state=present
  notify:
    - Restart php
    - Reload nginx
  with_items:
    - php7.2-xdebug

- name: Create /etc/php/7.2/mods-available/xdebug.ini
  template: src=xdebug.ini.j2 dest=/etc/php/7.2/mods-available/xdebug.ini owner=root group=root mode=0644
  notify: Restart php

- name: Symlink /etc/php/7.2/fpm/conf.d/xdebug.ini
  file: src=/etc/php/7.2/mods-available/xdebug.ini dest=/etc/php/7.2/fpm/conf.d/20-xdebug.ini state=link owner=root group=root mode=0644
  notify: Restart php

- name: Symlink /etc/php/7.2/cli/conf.d/xdebug.ini
  file: src=/etc/php/7.2/mods-available/xdebug.ini dest=/etc/php/7.2/cli/conf.d/20-xdebug.ini state=link owner=root group=root mode=0644
